version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  open-pull-requests-limit: 0
  schedule:
    interval: "monthly"
    day: "friday"
    time: "13:00"
    timezone: "America/Los_Angeles"
