name: ci

on:
  pull_request:
    branches: [ main ]

  # Ensure this workflow can be run manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build binaries
        run: make -f build.mk xcompile

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: go test ./...

  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout 5m0s
